### ISSUE TITLE
안녕하십니까

### ISSUE THREAD

**Issue by johndpope** [koreanwglasses/next-with-sockets#1]
I found your code - I have this code legacy javascript code - 

```javascript
/**
 * Handles incoming webhooks from Plaid.
 * https://plaid.com/docs/#webhooks
 */
router.post(
  '/webhook',
  asyncWrapper(async (req, res) => {
    console.log("🍌 webhook request:",req);
    console.log("res:",res);
    
    const { webhook_type: webhookType } = req.body;
    const { io } = req;
    const type = webhookType.toLowerCase();
    // There are five types of webhooks: AUTH, TRANSACTIONS, ITEM, INCOME, and ASSETS.
    // @TODO implement handling for remaining webhook types.
    const webhookHandlerMap = {
      transactions: handleTransactionsWebhook,
      item: handleItemWebhook,
    };
    const webhookHandler = webhookHandlerMap[type] || unhandledWebhook;
    webhookHandler(req.body, io);
    res.json({ status: 'ok' });
  })
);
```
i convert entire library over to typescript - but I get this error...
There's no io in nextapirequest ....
<img width="1150" alt="Screen Shot 2021-11-26 at 5 06 39 pm" src="https://user-images.githubusercontent.com/289994/143534738-21938c3c-134c-47e9-9ffd-c95d9e9eb435.png">

how can I convert this one variable? 
<img width="1158" alt="Screen Shot 2021-11-26 at 5 16 13 pm" src="https://user-images.githubusercontent.com/289994/143535593-a8c86fd7-0cf6-45d8-8ed5-b369134e8558.png">

**Comment by koreanwglasses** [comment]
반갑습니다~

I think what you're looking for is a type declaration that tells the compiler that `io` exists in `req`. Unfortunately, because `NextApiRequest` and `NextApiResponse` are declared as type aliases instead of interfaces, its not possible to take advantage of declaration merging to extend those types.

Currently, the "best" way is probably to declare a new type such as
```ts
import { NextApiRequest, NextApiResponse } from "next";
import { Server as IO } from "socket.io";

type NextApiRequestWithIO = NextApiRequest & { io: IO }

/* ... */

async function _post(req: NextApiRequestWithIO, res: NextApiResponse) {

  /* ... */

  const { io } = req; // `io` should have type IO

  /* ... */

}
```

For me, since io would be present on every `NextApiResponse` in my app, I preferred not to declare a new type alias with a new name. Instead, I took this hacky workaround to get the proper types in my code:

```ts
// src/types.d.ts

import { Server, Socket } from "net";
import { NextApiResponse as NextApiResponse_ } from "next"; // Import the original type as a different name
import { Server as IO } from "socket.io";

declare global { // declare global (instead of module scope)
  // This type is now present globally 
  type NextApiResponse<T = any> = NextApiResponse_<T> & { 
    socket: Socket & {
      server: Server & {
        io: IO;
      };
    };
  };
}
```

Its used like so:

```ts
// src/pages/api/ping.ts

import type { NextApiRequest } from "next"; // Note that I didn't import `NextApiResponse`

/* ... */

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse // Will infer as the type defined in the global scope above
) {

  /* ... */

  const io = res.socket.server.io; // `io` will have the correct type

  /* .... */

}
```

One difference to note between your code and mine: Your `io` is in the request, but I have my `io` in the response as was done in [this sandbox](https://codesandbox.io/s/piffv?file=/src/pages/api/socketio.ts). As my library is still new, I wouldn't expect that my approach is the best way, so be sure to use your best judgement here on which pattern to use. I might even experiment with cleaner ways to keep track of `io` myself.

Hope this helps. Good luck!

**Comment by johndpope** [comment]
thanks so much. 🙌
